config/routes.rb
Avalon::Application.routes.draw do
  resources :games do
    member do
      post 'join'
      post 'start'
      post 'kill'
      post 'leave'
      post 'restart'
      post 'refresh'
    end
    collection do
      get 'list'
      get 'open'      
    end
  end
   
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  root 'games#index'

  
  

end

app/models/.#game.rb
cobranet@ubuntu.2960:1441378819

app/models/character.rb
class Character < ActiveRecord::Base
  def self.get(oznaka)
    Character.where(:oznaka => oznaka).first
  end
end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :user
  has_many :players
  @@MINIONS = ["B","H","E","D"]
  @@MERLIN_SEE = ["B","H","E","F"]
  @@MESSAGES = { "A" => "Bad gays are",
                 "B" => "We are the power",
                 "C" => "You know of Merlin",
                 "D" => "Merlin can't se you and We are the power",
                 "E" => "Percival can't tell diference and we are the power",
                 "F" => "You know nothing",
                 "G" => "You know nothing",
                 "H" => "We are the power",
                 "I" => "You know nothing",
                 "J" => "You know nothing",
                 "K" => "You know nothing",
                 "L" => "You know nothing",
                 "M" => "We are the power",
                 "N" => "We are the power" }
    
                 
  def start
    self.status = 1
    self.players.create(:user_id => self.user_id)
    add_roles
    self.save!
  end

  def restart
    self.status = 1
    add_roles
    self.save!
  end
  
  def my_role(user_id)
    self.players.each do |p|
      if  p.user_id == user_id
        return p.role
      end
    end  
  end
  
  def kill_game
    self.status = 2
    self.save!
  end
  def json_data(user_id)
    data = {}
    data['game_id'] = self.id
    data['players'] = []
    self.players.each do |p|
      u = User.find(p.user_id) 
      data['players'] << { 'user_name' => u.name, 'image' => u.image }
    end 
    data['game_status'] = self.status
    v = Variant.find(self.variant)
    data['variant'] = { 'desc' => v.description, 'oznake' => v.oznake }
    if self.status == 1
      role = self.my_role(user_id)
      data['you_are'] = role
      data['message'] = @@MESSAGES[role]
    end 
    data.to_json
  end
  def leave_game(user_id)
    self.players.each do |player|
      if user_id == player.user_id
        player.delete
        player.save!
      end
    end
    self.save!
  end
  
  def self.user_game(user_id)
    Game.where("status = 1 or status = 0").to_a.each do |g|

      if g.user_id == user_id
        return g.id
      end
      
      if g.players.map { |x| x.user_id }.include?(user_id)
        return g.id
      end
    end
    return nil
  end
  
  def is_startable?
    return self.players.size == Variant.find(self.variant).num_of_players - 1 # all but owner
  end
  def is_restartable?
    return self.players.size == Variant.find(self.variant).num_of_players  # all 
  end

  def reveal_to(role)
    #Merlin 
    if role == "A"
      return @@MINIONS.append("F")
    end  
  end
  
  def who_is(role)
    arr = []
    self.players.each do |p|
      if role == p.role
        arr << p.user_id
      end
    end
    arr[0]
  end
  
  def minions
    arr = []
    self.players.each do |p|
      if @@MINIONS.include?(p.role) 
          arr << p.user_id
      end
    end
    arr
  end

  def merlin_see
    arr = []
    self.players.each do |p|
      if @@MERLIN_SEE.include?(p.role) 
          arr << p.user_id
      end
    end
    arr
  end
    
  
  def add_roles
    variant = Variant.find(self.variant)
    arr = []
    (0..variant.oznake.size-1).each do |x|
      arr << variant.oznake[x]
    end
    arr.shuffle.each_with_index do |oznaka,index|
      if players[index] 
        self.players[index].role = oznaka
        self.players[index].save!
      end 
    end
  end
  
end

app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :game
end

app/models/user.rb
require 'open-uri'
class User < ActiveRecord::Base
  include ActionView::Helpers::AssetUrlHelper
  has_many :games
  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.image = auth.info.image
      user.location = auth.info.location
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
      
    end
  end

  def format_image_name
    path = Rails.root.join("app","assets","images","users")
    "#{path}/user#{self.id}.png"
  end
  
  def download_image
    open(format_image_name, 'wb') do |file|
      file << open(self.image.gsub(/http/,"https")).read
    end
    self.haveimage = 1
    self.save!
  end
                   
  def image_file
    if self.haveimage == 1 &&  Rails.env.production? == false
    #      asset_url("assets/users/user#{self.id}.png")
            asset_url("assets/users/user#{self.id}.png")
    else
      download_image
      self.image
    end
  end
end

app/models/variant.rb
class Variant < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
#    @current_user = User.find(4)

  end

  helper_method :current_user
 
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  
  def index
    if current_user
      g = Game.user_game(current_user.id)
      if g
        redirect_to game_url(g)
        return
      end
    end
    
    respond_to do |format|
      format.html
      format.json { render :json => {state: "LOGIN" } }
    end  
  end

  def refresh
    g = Game.user_game(current_user.id)
    redirect_to game_url(g)
  end
  
  def leave
    @game = Game.find_by_id(params[:id])
    @game.leave_game(current_user.id)
    redirect_to games_path
  end
  
  def show
    @game = Game.find_by_id(params[:id])
    if  @game == nil || Game.user_game(current_user.id) != @game.id
      redirect_to games_url
      return 
    end
    
    @variant = Variant.find(@game.variant)
    if @game.status == 1
      @Iam = @game.my_role(current_user.id)
    end
    respond_to do |format|
      format.html
      format.json { render :json => @game.json_data(current_user.id) }
    end
  end 

  def list
    @opengames = Game.where(:status => 0).all
  end

  def kill
    @game = Game.find(params[:id])
    @game.kill_game
    redirect_to games_path
  end

  def open
    @game = Game.new
  end
  
  def join
    g = Game.find(params[:id])
    g.players.create(:user_id => current_user.id)
    redirect_to game_url(g)
  end

  def start
    g = Game.find(params[:id])
    g.start
    redirect_to game_url(g)
  end

  def restart
    g = Game.find(params[:id])
    g.restart
    redirect_to game_url(g)
  end
  
  def create
    
    v = Variant.where(description: params[:variant], num_of_players: params[:num_play]).first
    if v == nil
      raise params.inspect
    end  
    g = Game.create( :user_id => current_user.id, :variant => v.id, :status => 0)
    redirect_to game_url(g)
  end


  # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params[:game].permit(:name,:roles)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url, :notice => "Signed in!"
  end

  def destroy
    u = :user_id.to_s.to_i
    g = Game.user_game(u)
    
    if g
      Game.find(g).leave_game(u)
    end  
    session[:user_id] = nil
    redirect_to root_url, :notice => "Signed out!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_buttons.html.erb
<%if (@game.is_startable? || @game.is_restartable? ) && current_user && current_user.id == @game.user_id   %>
       <div class = "col-md-2">
          <% if @game.status == 0 %>
            <%= link_to "Start", start_game_path(@game),
	                         id: "start",
	                         class: "btn btn-primary btn-lg",
	                         method: "post"   %>
          <% end %>
       </div>
       <div class = "col-md-2">
          <%= link_to "Restart", restart_game_path(@game),
	                         id: "restart",
	                         class: "btn btn-primary btn-lg",
	                         method: "post"   %>
       </div>
  <div class = "col-md-2">
            <%= link_to "Kill", kill_game_path(@game),
	                         id: "kill",
	                         class: "btn btn-primary btn-lg",
	                         method: "post"   %>
       </div>
 <% end %>



 <%if current_user && current_user.id != @game.user_id  %>
       <div class = "col-md-2">
            <%= link_to "Leave", leave_game_path(@game),
	                         id: "leave",
	                         class: "btn btn-primary btn-lg",
	                         method: "post"   %>
       </div>
       <div class = "col-md-2">
            <%= link_to "Refresh", refresh_game_path(@game),
	                         id: "refresh",
	                         class: "btn btn-primary btn-lg",
	                         method: "post"   %>
       </div>
 <% end %>

    

app/views/games/_chars.html.erb
<div class="row chars" id="chars">
  <% (0..@variant.oznake.size-1).each do |i| %>
    <div class="col-md-2">
      <% cha = Character.get(@variant.oznake[i])%>
      <div id='<%="cha#{cha.oznaka}"%>'>
        <%= image_tag cha.image %>
      </div>
    </div>
  <% end %>
</div>

app/views/games/_current_user.html.erb
<div class="row current_user">
  <div class = "col-md-12">
    <div class="row">
      <div class="col-md-6">
	<%= link_to "Sign out", signout_path, id: "sign_out" %>
	<%= image_tag current_user.image_file %>
	<%= current_user.name %>
      </div>

      <div class="col-md-6">
	      <%= render partial: 'buttons' %>
      </div>
    </div>
  </div>
</div>

app/views/games/_jumbo.html.erb
<div class="row">
  
   <div class="col-md-4">
     <%= image_tag "avalon.png", size: "300x250" %> 
     <p>
       This site will choose character for you and send information that you need
     </p>
   </div>
	 
   <div class="col-md-8">
     <% if current_user %>
       <div class="row">
         <%= render partial: 'current_user' %>
	 <h2>
	   <%= link_to "Join",list_games_path,class:"btn btn-large btn-primary" %>
	 </h2>
       </div>
       <div class="row">
         <h2>
           <%= link_to "Create",open_games_path,class:"btn btn-large btn-primary" %>
         </h2>
       </div>	 
     <% else %>
       <%= render partial: 'sign_in' %>
     <%end%>

   </div>
</div>

app/views/games/_merlin.html.erb
Bad gays are 
<% @game.merlin_see.each do |bad| %>
  <% user = User.find(bad) %>
  <%= image_tag user.image , alt: user.name    %>
<% end %>

app/views/games/_new_game_form.html.erb
    <%= form_tag games_path  do  %>
      <div class="form-group">
	<label for="num_play">Broj igrača</label>
	<%= select_tag  "num_play",options_for_select((5..10).collect{ |x|  x }), {class: "form-control",id: "sel_num_play"   } %>
     </div>   
     <div class="form-group">
	<label for="variant">Varijanta</label>
	<%= select_tag "variant", options_for_select(Variant.all.collect{ |v| [v.description, v.description] }.uniq) , {class:   "form-control"}   %>
     </div>
        <%= submit_tag "Open game",class: "btn btn-large btn-primary"  %>
    <% end %>

app/views/games/_players.html.erb
   <div class="row players">
     <div class="col-md-1 game_owner">
       Main
       <%= image_tag   @game.user.image_file %>
     </div>
     <div class="col-md-1">
	 Players
     </div>

     <% for player in @game.players do %>
       <div class="col-md-1">
         <%= image_tag User.find(player.user_id).image_file %>
       </div>
     <% end %>

   </div>

app/views/games/_sign_in.html.erb
<h2>
  <%= link_to "Sign in with Facebook", "/auth/facebook",
      id: "sign_in",
      class: "btn btn-primary btn-lg" %>
</h2>

app/views/games/_start_button.html.erb
 <%if @game.is_startable? && current_user && current_user.id == @game.user_id   %>
       <div class = "col-md-2">
          <% if @game.status == 0 %>
            <%= link_to "Start", start_game_path(@game),
	                         id: "start",
	                         class: "btn btn-primary btn-lg",
	                         method: "post"   %>
          <% end %>
       </div>
 <% end %>
 <%if current_user && current_user.id == @game.user_id   %>
       <div class = "col-md-2">
            <%= link_to "Kill", kill_game_path(@game),
	                         id: "kill",
	                         class: "btn btn-primary btn-lg",
	                         method: "post"   %>
       </div>
 <% end %>

    

app/views/games/index.html.erb
<% content_for :head do %>
<div class="jumbotron">
    <div class="container">
      <%= render partial: 'jumbo' %>
    </div>
</div>
<%end%>

app/views/games/list.html.erb
<% content_for :main do %>
  <div class="col-md-6">
    <% for game in @opengames do %>
    <div class="row">

         <div class="col-md-1"> 
	  <%= game.id %>
	</div>
	 <div class="col-md-1"> 
	  <%= image_tag game.user.image %>
	 </div>
     <% for player in Game.find(game.id).players do %>
       <div class="col-md-1">
         <%= image_tag User.find(player.user_id).image %>
       </div>
     <% end %>.

	 <div class="col-md-7">
	   <%= link_to "Join", join_game_path(game), id: "join", class: "btn btn-primary btn-lg",method: "post"   %>
	   </div>
      </div>	
    <% end %>
  </div>  
<% end %>

app/views/games/open.html.erb
<% content_for :main do %>
  <%=render partial: "new_game_form" %>
<% end %>

app/views/games/show.html.erb
<% content_for :main do %>
  <%= render partial: 'current_user' %>
  <%= render partial: 'players' %>
  <%= render partial: 'chars' %>
<% end %>

   <% if @game.status == 1 %>   

   <% content_for :what_i_know do %>

   <% c = Character.get(@Iam) %>
   <%= "You are #{c.name}" %>
   <%= image_tag c.image  %>
   
   <% if @Iam == "A"%>
     <%= render partial: 'merlin' %>
   <% end %>

   
   <% if ["G","F","I","J","K","L"].include?(@Iam)  %>
   You have no clue who is who?
   <% end %>

   
   <% if ["B", "H","E"].include?(@Iam) %>
      We are the power!!
      <% @game.minions.each do |bad| %>
      <% user = User.find(bad) %>
        <%= image_tag user.image_file,alt: user.name %>
      <% end %>
   <% end %>

   <% if "C" ==  @Iam %>
      You know of Merlin
        <% user = User.find_by_id(@game.who_is("A")) %>
	<% if user %>
        <%= image_tag user.image_file, alt: user.name  %>
	<%end %>

        <% user = User.find_by_id(@game.who_is("E")) %>
	<% if user %>
        <%= image_tag user.image_file, alt: user.name %>
	<%end%>
   <% end %>

   <% if "D" ==  @Iam %>
      Merlin can't see you, we are the power.
        <% @game.minions.each do |bad| %>
	<% user = User.find(bad) %>
        <%= image_tag user.image_file, alt: user.name %>
      <% end %>
 
   <% end %>
      
<% end %>
<% end %>   

   

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Avalon</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">

    <div class="row">
      <div class="col-md-12">
	<%= yield :head  %>
      </div>
    </div>  

    <div class="row">
      <div class="col-md-12">
	<%= yield :main  %>
      </div>
    </div>

   <div class="row">
      <div class="col-md-12">
	<%= yield :what_i_know %>
      </div>
    </div>  

  </div>
  
</body>
</html>